spring.application.name=APIGateway

server.port=8000

client-id=ApiGateway
user-role=client
server-url=http://localhost:8080
realm-name=Cinema
client-secret=Qe7HnVAClBjgZabE0ZDSsVZTvzewjVI1

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/Cinema
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

eureka.client.service-url.defaultZone=http://localhost:8081/eureka

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

# ShowtimeController
spring.cloud.gateway.server.webflux.routes[0].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/showtimes
spring.cloud.gateway.server.webflux.routes[0].predicates[1]=Method=GET

spring.cloud.gateway.server.webflux.routes[1].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/showtimes
spring.cloud.gateway.server.webflux.routes[1].predicates[1]=Method=POST

spring.cloud.gateway.server.webflux.routes[2].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/showtimes/*
spring.cloud.gateway.server.webflux.routes[2].predicates[1]=Method=PUT

spring.cloud.gateway.server.webflux.routes[3].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/showtimes/*
spring.cloud.gateway.server.webflux.routes[3].predicates[1]=Method=DELETE

spring.cloud.gateway.server.webflux.routes[4].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/showtimes/movies
spring.cloud.gateway.server.webflux.routes[4].predicates[1]=Method=GET

spring.cloud.gateway.server.webflux.routes[5].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/showtimes/price
spring.cloud.gateway.server.webflux.routes[5].predicates[1]=Method=GET

spring.cloud.gateway.server.webflux.routes[6].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/showtimes/price/*
spring.cloud.gateway.server.webflux.routes[6].predicates[1]=Method=GET

spring.cloud.gateway.server.webflux.routes[7].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/showtimes/hall/*
spring.cloud.gateway.server.webflux.routes[7].predicates[1]=Method=GET

# CinemaController
spring.cloud.gateway.server.webflux.routes[8].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/cinemas
spring.cloud.gateway.server.webflux.routes[8].predicates[1]=Method=GET

spring.cloud.gateway.server.webflux.routes[9].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/cinemas/*
spring.cloud.gateway.server.webflux.routes[9].predicates[1]=Method=GET

spring.cloud.gateway.server.webflux.routes[10].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/api/cinemas
spring.cloud.gateway.server.webflux.routes[10].predicates[1]=Method=POST

spring.cloud.gateway.server.webflux.routes[11].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/api/cinemas/*
spring.cloud.gateway.server.webflux.routes[11].predicates[1]=Method=PUT

spring.cloud.gateway.server.webflux.routes[12].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/api/cinemas/*
spring.cloud.gateway.server.webflux.routes[12].predicates[1]=Method=DELETE

#HallController
spring.cloud.gateway.server.webflux.routes[13].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[13].predicates[0]=Path=/api/halls/*
spring.cloud.gateway.server.webflux.routes[13].predicates[1]=Method=GET

spring.cloud.gateway.server.webflux.routes[14].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[14].predicates[0]=Path=/api/halls
spring.cloud.gateway.server.webflux.routes[14].predicates[1]=Method=POST

spring.cloud.gateway.server.webflux.routes[15].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[15].predicates[0]=Path=/api/halls/*
spring.cloud.gateway.server.webflux.routes[15].predicates[1]=Method=PUT

spring.cloud.gateway.server.webflux.routes[16].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[16].predicates[0]=Path=/api/halls/*
spring.cloud.gateway.server.webflux.routes[16].predicates[1]=Method=DELETE

#HallTypeController
spring.cloud.gateway.server.webflux.routes[17].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[17].predicates[0]=Path=/api/hall-types
spring.cloud.gateway.server.webflux.routes[17].predicates[1]=Method=GET

spring.cloud.gateway.server.webflux.routes[18].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[18].predicates[0]=Path=/api/hall-types
spring.cloud.gateway.server.webflux.routes[18].predicates[1]=Method=POST

spring.cloud.gateway.server.webflux.routes[19].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[19].predicates[0]=Path=/api/hall-types/*
spring.cloud.gateway.server.webflux.routes[19].predicates[1]=Method=PUT

spring.cloud.gateway.server.webflux.routes[20].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[20].predicates[0]=Path=/api/hall-types/*
spring.cloud.gateway.server.webflux.routes[20].predicates[1]=Method=DELETE

#MovieController
spring.cloud.gateway.server.webflux.routes[21].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[21].predicates[0]=Path=/api/movies
spring.cloud.gateway.server.webflux.routes[21].predicates[1]=Method=GET

spring.cloud.gateway.server.webflux.routes[22].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[22].predicates[0]=Path=/api/movies/*
spring.cloud.gateway.server.webflux.routes[22].predicates[1]=Method=GET

spring.cloud.gateway.server.webflux.routes[23].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[23].predicates[0]=Path=/api/movies
spring.cloud.gateway.server.webflux.routes[23].predicates[1]=Method=POST

spring.cloud.gateway.server.webflux.routes[24].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[24].predicates[0]=Path=/api/movies/*
spring.cloud.gateway.server.webflux.routes[24].predicates[1]=Method=PUT

spring.cloud.gateway.server.webflux.routes[25].uri=lb://CinemaService
spring.cloud.gateway.server.webflux.routes[25].predicates[0]=Path=/api/movies/*
spring.cloud.gateway.server.webflux.routes[25].predicates[1]=Method=DELETE

#OrderController
spring.cloud.gateway.server.webflux.routes[26].uri=lb://OrderService
spring.cloud.gateway.server.webflux.routes[26].predicates[0]=Path=/api/orders
spring.cloud.gateway.server.webflux.routes[26].predicates[1]=Method=POST

spring.cloud.gateway.server.webflux.routes[27].uri=lb://OrderService
spring.cloud.gateway.server.webflux.routes[27].predicates[0]=Path=/api/orders/status/*
spring.cloud.gateway.server.webflux.routes[27].predicates[1]=Method=GET

spring.cloud.gateway.server.webflux.routes[28].uri=lb://OrderService
spring.cloud.gateway.server.webflux.routes[28].predicates[0]=Path=/api/orders/reserved/*
spring.cloud.gateway.server.webflux.routes[28].predicates[1]=Method=GET

#PaymentController
spring.cloud.gateway.server.webflux.routes[29].uri=lb://OrderService
spring.cloud.gateway.server.webflux.routes[29].predicates[0]=Path=/api/payment
spring.cloud.gateway.server.webflux.routes[29].predicates[1]=Method=POST

spring.cloud.gateway.server.webflux.routes[30].uri=lb://OrderService
spring.cloud.gateway.server.webflux.routes[30].predicates[0]=Path=/api/payment/refund/*
spring.cloud.gateway.server.webflux.routes[30].predicates[1]=Method=POST